[build-system]
requires = ["uv_build>=0.10.3,<0.11.0"]
build-backend = "uv_build"

[project]
name = "keboola_streamlit"
version = "v0.1.3"
dependencies = [
    "streamlit>=1.37.0",
    "pandas",
    "kbcstorage",
    "deprecated",
    "snowflake-snowpark-python>=1.35.0",
]
requires-python = ">=3.10"
authors = [
    {name = "pandyandy", email = "andrea.novakova@keboola.com"},
    {name = "yustme", email = "vojta.tuma@keboola.com"},
]
description = "A Python library that simplifies Keboola SAPI integration in Streamlit apps."
readme = "README.md"
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Repository = "https://github.com/keboola/keboola_streamlit/"

[dependency-groups]
dev = [
    "pytest",
    "pre-commit",
]

[tool.ruff]
line-length = 120
